### ISSUE TITLE
A sample project about using IGameInputDevice::CreateForceFeedbackEffect 

### ISSUE THREAD

**Issue by luqiming666** [microsoft/Xbox-GDK-Samples#27]
Is there any sample project for demonstrating the using the following APIs?
IGameInputDevice::CreateForceFeedbackEffect 
IGameInputForceFeedbackEffect::SetState
IGameInputForceFeedbackEffect::SetGain
IGameInputForceFeedbackEffect::SetParams

If yes, let me know. If not, any plan to make one?
Thanks.

**Comment by BrianPeek** [comment]
The sample in System\SimpleFFBWheel demonstrates some of these APIs. There is a new version of this sample coming with the March GDK release.

**Comment by luqiming666** [comment]
Cool. 

Then my question would be, are those force feedbacks designed only for racing wheel? Is it possible for them to be applied to gamepads?
I mean those types of force feedback like ramp, sineWave, squareWave, spring, etc.
https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/reference/input/gameinput/structs/gameinputforcefeedbackparams

BTW, what does GameInput device with GameInputKindUiNavigation look like? It would be nice if you can show me a picture.

I also found that SimpleFFBWheel doesn't have a Gaming.Desktop.x64 configuration like GamepadVibration. Does it mean it won't run on a Windows PC?

Thank you for your help.

**Comment by BrianPeek** [comment]
The effects are only for devices which have force-feedback motors, which at the moment are most supported in steering wheels. These will not work for gamepads at all.  FFB is supported on both Desktop and Console, however there are a few issues on Desktop which is why we don't have a build for Desktop.  This will be fixed in a future release and the sample updated.
